# @see https://github.com/possi/MineVive/blob/master/src/main/resources/config.yml

viveOnly:
  ## Kick all Players not using Vive-Minecrift, so that only teleporting users are on the Server
  enable: false

  ## Kick-Message for Non-Vivers
  message: "This Server requires you to use Minecrift for Vive: https://github.com/Automat-GH/minecrift"

  ## The timeout before a non-vive player gets kicked. You may increase thit, if you assume false-positiv kicks
  ## In ticks: so 10 is half a second. 20 for one second, 40 for two seconds, and so on
  waitTimeout: 10

## Give player this Items always (but only one time)
alwaysItem:
  # e.g. "MAP" for Map (@see https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Material.java)
  item:

  # e.G. Map-Id
  data:

## Sets Prefix to Player names (Doesn't work yet with Essentials Display Names or Permissions Prefixes)
prefix:
  ## Prefix for Players using Minecrift for Vive
  ## Example: "&4[Vive]&r "
  vive:

  ## Prefix for all other Players (Classic users)
  vanilla:

## Groups a Player will be added to (additional to groups he already has)
## This requires Vault and a supported Permission-Plugin with Multi-Group-Support (e.g. PermissionEx)
groups:
  ## Group for Players using Minecrift for Vive
  vive:

  ## Group for Non-Vive-Players
  vanilla:

  ## Group for Non-Teleporting-Movement (in Addition to vive-Group)
  ## Assumen that all Players are using teleportation by default, because of that there is no Teleporting-Group
  freemove:

## Disable PVP between Non-Vive and Vive-Players
pvp:
  sameTypeOnly: false

  ## Also Prevent Splash-Potions (Healing Potions are prevented also)
  preventPotion: true